var Id = 1;
var instructorName = "nahid";
var instructor = [1, "nahid"];
var user;
user = [1, "joe", true, 20, "joe"];
console.log(user);
console.log(instructor);
var employee;
employee = [[1, 'joe'], [2, 'front'], [3, 'back']];
console.log(employee);
